import type { LucideIcon } from 'lucide-react';
import {
  Antenna,
  Apple,
  Baby,
  Backpack,
  BedDouble,
  Bike,
  BookOpen,
  Briefcase,
  Building,
  Bus,
  Calendar,
  Camera,
  Car,
  ChefHat,
  Clipboard,
  Cloud,
  Coffee,
  Coins,
  CookingPot,
  Cpu,
  Dumbbell,
  Flower,
  Gamepad,
  Gift,
  Glasses,
  GraduationCap,
  HardDrive,
  Heart,
  Home,
  Key,
  Lamp,
  Laptop,
  Monitor,
  Music,
  Network,
  PartyPopper,
  Palette,
  PawPrint,
  Phone,
  Pizza,
  Plane,
  Printer,
  Puzzle,
  Router,
  Scissors,
  Server,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Smartphone,
  Sofa,
  Sprout,
  Sun,
  Tablet,
  Tent,
  Toilet,
  Trees,
  Truck,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  WashingMachine,
  Watch,
  Wifi,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  building: Building,
  'bed-double': BedDouble,
  sofa: Sofa,
  lamp: Lamp,
  key: Key,
  'washing-machine': WashingMachine,
  'shower-head': ShowerHead,
  toilet: Toilet,
  utensils: Utensils,
  'cooking-pot': CookingPot,
  'shopping-cart': ShoppingCart,
  'shopping-basket': ShoppingBasket,
  sprout: Sprout,
  trees: Trees,
  flower: Flower,
  sun: Sun,
  umbrella: Umbrella,
  tent: Tent,
  car: Car,
  bike: Bike,
  plane: Plane,
  truck: Truck,
  bus: Bus,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  wallet: Wallet,
  coins: Coins,
  calendar: Calendar,
  printer: Printer,
  clipboard: Clipboard,
  backpack: Backpack,
  watch: Watch,
  glasses: Glasses,
  scissors: Scissors,
  puzzle: Puzzle,
  palette: Palette,
  coffee: Coffee,
  apple: Apple,
  pizza: Pizza,
  'chef-hat': ChefHat,
  heart: Heart,
  baby: Baby,
  'paw-print': PawPrint,
  gift: Gift,
  'party-popper': PartyPopper,
  dumbbell: Dumbbell,
  music: Music,
  camera: Camera,
  gamepad: Gamepad,
  monitor: Monitor,
  laptop: Laptop,
  tablet: Tablet,
  smartphone: Smartphone,
  router: Router,
  wifi: Wifi,
  server: Server,
  cloud: Cloud,
  'hard-drive': HardDrive,
  cpu: Cpu,
  network: Network,
  antenna: Antenna,
  tv: Tv,
  phone: Phone,
};

/**
 * Icono de proyecto. Si `name` es un icono Lucide del catálogo lo pinta como
 * SVG (sigue el tema); si no (emoji legado guardado antes del selector) lo
 * renderiza como texto para no perder datos.
 */
export function ProjectIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICON_MAP[name];
  if (Icon) {
    return <Icon className={className} aria-hidden="true" />;
  }
  return (
    <span className={className} aria-hidden="true">
      {name}
    </span>
  );
}
